config/routes.rb
Rails.application.routes.draw do
	resources :alien_races, only: [:index, :show, :create, :new]
	resources :planets, only: [:index, :show, :create, :new]
	resources :populations, only: [:create, :new, :show]

	root to: "planets#root"
end

app/models/alien_race.rb
class AlienRace < ApplicationRecord
	has_many :populations
	has_many :planets, through: :populations

	validates :name, presence: true
	validates :biome, presence: true
	validates :demeanor, presence: true
	validates :description, presence: true

	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
	has_many :populations
	has_many :alien_races, through: :populations
end

app/models/population.rb
class Population < ApplicationRecord
  belongs_to :planet
  belongs_to :alien_race
end

app/controllers/alien_races_controller.rb
class AlienRacesController < ApplicationController

	def index
		@alien_races = AlienRace.all
	end

	def show
		@alien_race = AlienRace.find(params[:id])
	end

	def new
		@alien_race = AlienRace.new
	end

	def create
		@alien_race = AlienRace.new(alien_race_params)

		if @alien_race.save
			redirect_to alien_race_path(@alien_race)
		else
			render :new
		end
	end

	private

	def alien_race_params
		params.require(:alien_race).permit(:name, :biome, :demeanor, :description)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController

	def create
		@population = Population.new(population_params)
		if @population.save
		else
		end
	end

	private

	def population_params
		params.require(:populations).permit(:size, :planet_id, :alien_race_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alien_races/index.html.erb
<h1>Alien Races</h1>

<ul>
	<% @alien_races.each do |alien_race| %>
		<li><%= link_to alien_race.name, alien_race_path(alien_race) %></li>
	<% end %>
</ul>

app/views/alien_races/new.html.erb
<% if @alien_race.errors.any? %>
	<ul>
	<% @alien_race.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @alien_race do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>	

	<%= f.label :biome %>
	<br>
	<%= f.text_field :biome %>
	<br>	

	<%= f.label :demeanor %>
	<br>
	<%= f.text_field :demeanor %>
	<br>

	<%= f.label :description  %>
	<br>
	<%= f.text_area :description  %>
	<br>

	<%= f.submit %>	

<% end %>

app/views/alien_races/show.html.erb
<h1><%= @alien_race.name %></h1>

<p>Biome: <%= @alien_race.biome %></p>
<p>Demeanor: <%= @alien_race.demeanor %></p>
<p>Description: <%= @alien_race.description %></p>


<h1>Populations</h1>
<% @alien_race.populations.each do |pop| %>
	<p>Planet: <%= pop.planet.name %></p>
	<p>Size: <%= pop.size %></p>
	<p>Extinct: <%= pop.extinct %></p>
	
<% end %>

<%= form_for :populations, url: populations_path do |f| %>
	<%= f.label :size %>
	<%= f.number_field :size %>
	<%= f.collection_select :planet_id, Planet.all, :id, :name %>
	<%= f.hidden_field :alien_race_id, value: @alien_race.id %>
	<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HHGG</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= link_to "Alien Races Index", alien_races_path%>
    <%= yield %>
  </body>
</html>